export const CREATE_QUESTION = 'CREATE_QUESTION'
export const INCREMENT_VIEW_COUNTER = 'INCREMENT_VIEW_COUNTER'
export const INCREMENT_ANSWER_COUNTER = 'INCREMENT_ANSWER_COUNTER'
export const CREATE_COMMENT = 'CREATE_COMMENT'
